[project]
name = "uwika-ta-31123022-2026"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.2.0",
    "ipython>=9.17.1",
    "matplotlib>=3.11.2",
    "networkx>=3.7",
    "numpy>=2.5.3",
    "osmnx>=2.1.1",
    "pandas>=3.0.6",
    "pyproj>=3.8.0",
    "scipy>=1.18.1",
    "shapely>=2.2.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyterlab>=4.6.4",
]
